# Generated by Django 5.0.7 on 2024-08-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrimCommand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("video_no", models.IntegerField()),
                ("start_time", models.IntegerField()),
                ("end_time", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="uploads/")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConcatCommand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("videos", models.ManyToManyField(to="videos.video")),
            ],
        ),
    ]
